### ISSUE TITLE
シェアボタンの実装　〆切8/25-31まで

### ISSUE THREAD

**Issue by yasui05821** [kfug/frontconf2019#17]
シェアボタンの実装をお願いします！
![image](https://user-images.githubusercontent.com/13504241/63257062-ec3f0b80-c2b3-11e9-8cce-b541de8f9ec7.png)

▼デザイン
https://xd.adobe.com/spec/832559c0-f598-4c9b-589c-e84769ff2fe5-f514/

<img width="71" alt="スクリーンショット 2019-08-19 19 00 53" src="https://user-images.githubusercontent.com/13504241/63256977-c3b71180-c2b3-11e9-9caa-c0da5bed2231.png">
右端のボタンを < / > に切り替えれば色とかも見れます〜

**Comment by takumiz19** [comment]
#18 こちらで対応してます
