### ISSUE TITLE
スポンサー個別紹介ページ作成

### ISSUE THREAD

**Issue by yasui05821** [kfug/frontconf2019#24]
![image](https://user-images.githubusercontent.com/13504241/64689436-515bda80-d4c9-11e9-936f-5539e40362da.png)

「「企業ページ」を見る」は各企業のURLを別タブで開きたいので `target=“_blank”  rel=“noopener noreferrer”`
の指定をお願いします。

ページ上部のヘッダーは #25 でも使用するため、別コンポーネントとして作成をお願いします。
`components/Header.vue` というファイルを作成しているのでそちらを利用してください。
中身はfooterのコピーしているだけなので、書き換えてください。

各パーツ等やhoverについてはすでに実装済みのセクションを参考にしてください。

画像については以下のXDのURLから書き出しが可能なのでお願いします。
画像はほかセクションと同様に背景画像として指定をお願いします。

▼デザインPC
https://xd.adobe.com/spec/78fa634a-aeb7-4b71-4cb5-52b4f3686fd3-0ecb/screen/d348e405-8d77-4577-9461-49c38046f301/-

▼デザインSP
https://xd.adobe.com/spec/78fa634a-aeb7-4b71-4cb5-52b4f3686fd3-0ecb/screen/3208a22c-05f2-41c2-bcf0-56964be0bead/-sp-1

**Comment by mikakane** [comment]
本文部分は v-html にて html テキストが入る予定ですので、 scss 記述の際には deep オペレータご利用ください。
