### ISSUE TITLE
yarnかnpmか、どちらかに統一

### ISSUE THREAD

**Issue by sayanaka** [kfug/frontconf2019#26]
webサイトに直接は関係ない、提案的な話ですが・・・。

リポジトリに、 `package-lock.json`と `yarn.lock`が混在していて、
* `yarn install` =>  `yarn dev`だとエラー
* `npm install` => `npm run dev`だと正常に動く

という問題が発生しています。

どちらかに統一すれば、こういう問題もなくなるのかなと思います。

**Comment by mikakane** [comment]
すみません、yarn.lock 削除しておきますー
