### ISSUE TITLE
ステッカーの作成

### ISSUE THREAD

**Issue by ririko25** [kfug/frontconf2019#39]
### 依頼内容

FRONTCONF 2019で配布する用のステッカーの作成をお願いします。

### 印刷、入稿に関して

入稿はグラフィックさんで以下の種類のステッカーを注文します。
https://www.graphic.jp/lineup/sticker/economy

シール印刷入稿データの注意
https://www.graphic.jp/data_guide/product/sticker
※ こちらをお読みになった上で作成のほどお願いします。

### 作成するステッカーの種類

- [x] KFUG
- [x] chatbox
- [x] LecCafe
- [ ]  FRONTCONF 2019

### それぞれのステッカーの作成に必要な情報
- KFUG
シール部分のサイズ：5cm×5cm

- chatbox
シール部分のサイズ：5cm×5cm

- LecCafe
シール部分のサイズ：5cm×5cm
備考：元データのロゴから「chatbox」の部分を削除したロゴでシールデータの作成をお願いします。

-  FRONTCONF 2019
シール部分のサイズ：A6 サイズの台紙に5cm×5cmのステッカを二つ並べて作成してください。
参考：https://drive.google.com/drive/u/1/folders/14XXyJcAWw_ZCEVraBq8WhnnLyUL2xwlk

### データ

それぞれの元デザインデータはこちらのドライブに集めております。https://drive.google.com/drive/u/1/folders/1VckGKebem8mPqw9vDgd021vvltSJDxq1

シールデータテンプレ(ai)
https://drive.google.com/drive/u/1/folders/14tgUZRL3pJsbBAVVY0yjLmWIZIpxVEGy

### 提出先

こちらのドライブに提出のほどよろしくお願い致します。
https://drive.google.com/drive/u/1/folders/1aFwey0oKT2SeQPEmUEL_BA1flXCQddyW

**Comment by msak717** [comment]
■FRONTCONF 2019はビットマップデータのためステッカーにできません

＞カットパスに画像（ビットマップデータ）は使用しないでください。
＞PDFやjpgなどの画像データは対応外です。
https://www.graphic.jp/data_guide/product/sticker

対応策として元の水彩画に近づけたベクターレイヤーで作成すると可能です。

ベクターとビットマップ（ピクセル）の違いについて
http://4geek.net/difference-bitmap-and-vector/

**Comment by msak717** [comment]
デザインアップしました。
ご確認お願いします。

https://drive.google.com/drive/u/1/folders/1KkMf0UNq_llxzjEHhhLF6stiWvjU7X9t

**Comment by msak717** [comment]
メモ

■FRONTCONF 2019について
一度模索。クオリティ&工数に関する懸念が生じるときは後藤さんに相談する
