### ISSUE TITLE
スクロール位置の調整

### ISSUE THREAD

**Issue by mikakane** [kfug/frontconf2019#59]
@frontkansai 公式サイト、リンククリックするとスクロール位置が前ページでクリックした位置になってるようなので、こちらのご確認・ご対応よろしくお願いいたします
gyazo.com/e14892854bfbea…

https://twitter.com/yamanoku/status/1181063192077725702

**Comment by mikakane** [comment]
対応しましった！

https://github.com/kfug/frontconf2019/commit/12a8124c3e33b1b4a7ccad09e5426e42c99c5e6d

**Comment by yamanoku** [comment]
LGTM 👍
