### ISSUE TITLE
【web用タイムテーブル】ライティング：premium部分

### ISSUE THREAD

**Issue by ririko25** [kfug/frontconf2019#66]
web用タイムーブルのpremium部分のライティングを以下の通りお願いします。

各　55文字　以内

1_優先参加席

2_会場内Wifi

3_領収書発行

4_優先受付

5_記念ノベルティ

![aaa](https://user-images.githubusercontent.com/29808916/66470921-79892a00-eac5-11e9-8b13-a0d72a37fe5f.jpg)

**Comment by mikakane** [comment]
優先参加シート

各セッションごとに、テーブル・電源付きの優先参加シートをご用意させていただきます。

会場内Wifi

会場内でご利用いただけるWifiをご提供させていただきます。
※ Wifi の通信設備はベストエフォートでの提供となるため、当日の状況により繋がりにくくなる可能性もございます。

領収書発行

運営より「セミナー参加費」品目で領収書を発行させていただきます。
法人で複数名参加の場合、まとめての領収書発行も可能です。

優先受付

当日朝混雑しがちな会場受付で、専用の受付を用意させていただきます。
朝イチからのご参加でもスムーズな入場が可能です。

記念ノベルティ

当日受付時にささやかではございますが記念品を用意させていただいております。

※ 優先参加シート、領収書発行の特典ご利用には、後日お送りするメールより事前申し込みが必要です。
